"""Update order item

Revision ID: 7c975c219bb6
Revises: 940c252cbb12
Create Date: 2023-06-08 16:53:46.106245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c975c219bb6'
down_revision = '940c252cbb12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitems', sa.Column('order_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderitems', 'order_date')
    # ### end Alembic commands ###
